In [25]:
import numpy as np #NumPy kütüphanesini np olarak ekler

In [27]:
dizi=np.array([1,2,3,3.14]) #dizi içine eklenen bir ondalık sayı, tam sayı olan diğer elemanları da ondalık sayı hâline 
dönüştürür
dizi

array([1.  , 2.  , 3.  , 3.14])

In [26]:
dizi=np.array([1,2,3,3.14],dtype=int) #NumPy dizilerini tanımlama sırasında dizideki tüm elemanları tek tipe dönüştürme işlemi gerçekleşir
dizi

array([1, 2, 3, 3])

In [28]:
birboyut=np.array([1,2,3]) #NumPy kütüphanesini import ettikten sonra aşağıdaki kodları yazarak bir boyutlu dizi oluşturur

birboyut

array([1, 2, 3])

In [29]:
ikiboyut = np.array([[1,2,3], [4,5,6]]) #İki boyutlu dizi oluşturur
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]]) #Üç boyutlu dizi oluşturur
ucboyut

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])