**numpy dizi işlemleri**

In [1]:
import numpy as np #numpy kütüphanesini np takma adı ile projeye dahil ediyoruz

In [2]:
dizi=np.full((4,3),5) #4satur 3 sütün oluşturup içerisine 5 ekler
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [5]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [6]:
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [ ]:
dizi=np.array([1,2,3])

In [ ]:
dizi=np.array([1,2,3.14])

In [48]:
dizi.dtype  #dizinin değişken türünü verir. numpy dizileinde elemanların hepsi aynı türdendir

dtype('int32')

In [10]:
dizi=np.array([1,2,3,],dtype=int)

**numpy ile farklı boyutlarda dizi oluşturma**

In [11]:
#bir boyutlu dizi oluşturma
bir_boyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
iki_boyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [12]:
bir_boyut

array([1, 2, 3, 4])

In [13]:
iki_boyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutucular**

In [14]:
np.zeros(7) #7 sınıfından oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3),dtype=int) #* sınıfından oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones(3)#3 tane 1 içeren bir NumPy dizisi oluşturur.

array([1., 1., 1.])

In [17]:
np.full((4,3),5)#5 sayısından oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
np.arange(2,22,5) #başlangıç,bitiş ve artış değerine göre dizi oluşturma

array([ 2,  7, 12, 17])

In [21]:
np.linspace(2,10,num=7) #başlangıç ve bitiş değeri aralığında belirtilen miktarda  eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [26]:
np.random.randint(0,10,5) #0-10 aralığında rastgele 5 sayıdan oluşan bir boyutlu dizi

array([4, 2, 0, 5, 7])

In [27]:
np.random.randint(0,10,(5,2)) #0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[2, 0],
       [7, 3],
       [9, 0],
       [9, 3],
       [6, 1]])

**diziler ile ilgili işlemler**

In [29]:
#dizilerin eleman sayısını öğrenmek için shape komutu kullanılşır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [30]:
#ndim dizi boyutunun öğrenmek için kullanılır
dizi.ndim

2

In [31]:
#size dizideki toplam eleman sayısını göterir
dizi.size

12

In [33]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinden değerini verir

4

**SORU**

5 satır 7 sütün alacak şekilde rastgele sayıdan oluşan int türünde bir dizi oluştur

In [52]:
np.random.randint(0,10,(5,7))

array([[2, 3, 5, 3, 4, 4, 6],
       [9, 7, 8, 5, 9, 9, 2],
       [4, 6, 0, 2, 6, 9, 2],
       [3, 7, 3, 6, 7, 0, 2],
       [7, 3, 0, 9, 7, 5, 4]])