**Numpy Dizi İşlemleri**

In [38]:
import numpy as np #numpy kütüphanesini no takma adı ile projeye dahil ediyoruz.

In [8]:
dizi=np.full((4,3),5) #5 sayısından oluşan 4*3'lük dizi
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
np.array([1,2,3]) #yeni numpy dizesi oluşturuyoruz.

array([1, 2, 3])

In [54]:
dizi=np.array([1,2,3.14],dtype=int) #dizideki tüm elemanları tek tipe dönüştürür. 
dizi

array([1, 2, 3])

In [56]:
dizi=np.array(["elma","erik","iğde"]) #Oluşturduğumuz diziyi bir değişkene aktarıyoruz.
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

**Numpy ile farklı boyutlarda dizi oluşturma**

In [26]:
birboyut=np.array([1,2,3]) #bir boyutlu dizi oluşturduk.
birboyut

array([1, 2, 3])

In [27]:
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #ikiboyutlu dizi oluşturduk.
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Numpy Yer Tutucular**

In [30]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlu dizi oluşturur.

array([0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((2,3),dtype=int) #2 satır 3 sütunluk iki boyutlu bir dizi oluşturur.

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.ones(3) #3 birden oluşan tek boyutlu dizi oluşturur.

array([1., 1., 1.])

In [35]:
np.full((4,3),5) #5 sayısından oluşan 2*3'luk dizi.

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
np.arange(2,22,5) #Başlangıç,bitiş ve artış değerine göre dizi oluşturur.

array([ 2,  7, 12, 17])

In [40]:
np.linspace(2,10,num=7) #Başlangıç ve bitiş değeri aralığında belirtilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [41]:
np.random.randint(0,10,5) #0-10 aralığında rastgele 5 sayıdan oluşan bir boyutlu dizi

array([4, 0, 5, 7, 6])

In [42]:
np.random.randint(0,10,(5,2)) #0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[0, 0],
       [8, 2],
       [1, 4],
       [6, 2],
       [1, 1]])

**Diziler ile ilgili işlemler**

In [43]:
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #dizilerin eleman sayısını öğrenmek için shape komutu kullanılır. 
dizi.shape

(3, 4)

In [44]:
dizi.ndim # ndim dizi boyutunu öğrenmek için kullanılır.

2

In [45]:
dizi.size #size dizesindeki toplam eleman sayısını gösterir. 

12

In [46]:
dizi. #dizideki her bir elemanın bayt cinsinden değerini verir.

4

**Örnek**

In [51]:
np.random.randint(0,10,(5,7)) #0-10 arasından 5 satır 7 sütunluk rastgele sayılar.

array([[9, 7, 9, 2, 0, 6, 1],
       [0, 3, 3, 6, 5, 1, 9],
       [1, 1, 1, 1, 1, 8, 9],
       [6, 1, 6, 2, 6, 4, 2],
       [1, 0, 3, 4, 8, 1, 8]])