In [4]:
import numpy as np #numpy kütphanesi np olarak ekler.
dizi=np.array([1,2,3,4,5]) #numpy atama dizisi işlemi için kullanılır.

In [5]:
dizi

array([1, 2, 3, 4, 5])

In [9]:
dizi=np.array([1,2,3.5,4.6]) #dizi içine eklenen bir ondalık sayı, tam sayı olan diğer elemanları da ondalık sayı hâline dönüştürür.
dizi

array([1. , 2. , 3.5, 4.6])

In [15]:
dizi=np.array([1,2,3,4.5],dtype=int) #dizilerini tanımlama sırasında dizideki tüm elemanları tek tipe dönüştürür.
dizi

array([1, 2, 3, 4])

In [17]:
birboyut=np.array([1,2,3,4,5]) #Bir boyutlu dizi oluşturmak için kullanılır.
birboyut

array([1, 2, 3, 4, 5])

In [18]:
ikiboyut=np.array([[1,2,3],[4,5,6]]) #İki boyutlu dizi oluşturmak için kulllanılır.
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
ucboyut=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]]) #Üç boyutlu dizi oluşturmak için kullanılır.
ucboyut

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [20]:
np.zeros(5) #zeros fonksiyonunu kullanarak sıfırlardan oluşan NumPy dizisi için kullanılır. 

array([0., 0., 0., 0., 0.])